name: Markdown validation

on:
  workflow_call:
    inputs:
      SYNTAX_CHECK_IGNORE_FILES:
        description: 'Multiple files must be separated with single space, eg "./one_file.md ./another_file.md"'
        required: false
        type: string
        default: ''

jobs:
  markdown_validation:
    name: Markdown validation
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up config files
      run: |
        wget https://raw.githubusercontent.com/uc-cdis/.github/master/.github/workflows/validate_markdown_lint.jsonc -P .github/workflows/
        wget https://raw.githubusercontent.com/uc-cdis/.github/master/.github/workflows/validate_markdown_links.json -P .github/workflows/

    - name: Check syntax
      uses: avto-dev/markdown-lint@v1.5.0
      with:
        config: '.github/workflows/validate_markdown_lint.jsonc'
        args: '**.md'
        ignore: ${{ inputs.SYNTAX_CHECK_IGNORE_FILES }}

    - name: Check dead links
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
      with:
        config-file: '.github/workflows/validate_markdown_links.json'
        use-quiet-mode: 'yes'
